// lib/themes.ts

export type ThemeConfig = {
  bg: string;               // page background
  card: string;             // card/surface background
  border: string;           // default border color
  borderAccent: string;     // accent border (e.g., selected state)
  accent: string;           // text color for accent elements
  accentBg: string;         // solid accent background (buttons)
  accentLight: string;      // light tint of accent (badges, icons)
  gradient: string;         // gradient string (from-* to-*)
  text: string;             // primary text color
  muted: string;            // secondary/muted text color
  isLight: boolean;         // whether theme is light (for conditional styles)
  inputBg: string;          // input field background
  inputBorder: string;      // input field border
  buttonHover: string;      // hover background for solid buttons
  progressBar: string;      // color for progress bar fill
  blob1: string;            // first blob background (for animated backgrounds)
  blob2: string;            // second blob background
  glow: string;             // box shadow glow effect using accent
};

export const THEME_CONFIG: Record<string, ThemeConfig> = {
  // Light Themes
  minimalist: {
    bg: 'bg-[#F8FAFC]',
    card: 'bg-white/80 backdrop-blur-3xl',
    border: 'border-slate-200',
    borderAccent: 'border-indigo-500',
    accent: 'text-indigo-600',
    accentBg: 'bg-indigo-600',
    accentLight: 'bg-indigo-50',
    gradient: 'from-indigo-600 to-blue-600',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-slate-50',
    inputBorder: 'border-slate-200',
    buttonHover: 'hover:bg-indigo-700',
    progressBar: 'bg-indigo-500',
    blob1: 'bg-indigo-300/20',
    blob2: 'bg-blue-300/20',
    glow: 'shadow-[0_20px_40px_rgba(99,102,241,0.1)]',
  },

  'library-sage': {
    bg: 'bg-[#FDF8F2]',
    card: 'bg-[#F5EFE4]/80 backdrop-blur-3xl',
    border: 'border-[#E2D6C0]',
    borderAccent: 'border-[#8B5E34]',
    accent: 'text-[#8B5E34]',
    accentBg: 'bg-[#8B5E34]',
    accentLight: 'bg-[#8B5E34]/10',
    gradient: 'from-[#8B5E34] to-[#5C3A21]',
    text: 'text-[#2D2420]',
    muted: 'text-[#7A5C4A]',
    isLight: true,
    inputBg: 'bg-[#F5EFE4]/50',
    inputBorder: 'border-[#E2D6C0]',
    buttonHover: 'hover:bg-[#6B4423]',
    progressBar: 'bg-[#8B5E34]',
    blob1: 'bg-[#8B5E34]/10',
    blob2: 'bg-[#5C3A21]/10',
    glow: 'shadow-[0_20px_40px_rgba(139,94,52,0.1)]',
  },

  'zen-garden': {
    bg: 'bg-[#F0FDF4]',
    card: 'bg-white/80 backdrop-blur-3xl',
    border: 'border-emerald-200',
    borderAccent: 'border-emerald-500',
    accent: 'text-emerald-600',
    accentBg: 'bg-emerald-600',
    accentLight: 'bg-emerald-50',
    gradient: 'from-emerald-500 to-teal-700',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-emerald-50/50',
    inputBorder: 'border-emerald-200',
    buttonHover: 'hover:bg-emerald-700',
    progressBar: 'bg-emerald-500',
    blob1: 'bg-emerald-300/20',
    blob2: 'bg-teal-300/20',
    glow: 'shadow-[0_20px_40px_rgba(16,185,129,0.1)]',
  },

  oceanBreeze: {
    bg: 'bg-[#F0F9FF]',
    card: 'bg-white/80 backdrop-blur-2xl',
    border: 'border-sky-200',
    borderAccent: 'border-sky-500',
    accent: 'text-sky-600',
    accentBg: 'bg-sky-600',
    accentLight: 'bg-sky-50',
    gradient: 'from-sky-400 to-blue-700',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-sky-50/50',
    inputBorder: 'border-sky-200',
    buttonHover: 'hover:bg-sky-700',
    progressBar: 'bg-sky-500',
    blob1: 'bg-sky-300/20',
    blob2: 'bg-blue-300/20',
    glow: 'shadow-[0_20px_40px_rgba(14,165,233,0.1)]',
  },

  sunrise: {
    bg: 'bg-[#FFFBEB]',
    card: 'bg-white/80 backdrop-blur-2xl',
    border: 'border-amber-200',
    borderAccent: 'border-amber-500',
    accent: 'text-amber-600',
    accentBg: 'bg-amber-600',
    accentLight: 'bg-amber-50',
    gradient: 'from-amber-400 via-orange-500 to-red-500',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-amber-50/50',
    inputBorder: 'border-amber-200',
    buttonHover: 'hover:bg-amber-700',
    progressBar: 'bg-amber-500',
    blob1: 'bg-amber-300/20',
    blob2: 'bg-orange-300/20',
    glow: 'shadow-[0_20px_40px_rgba(245,158,11,0.1)]',
  },

  lavenderDream: {
    bg: 'bg-[#FAF5FF]',
    card: 'bg-white/80 backdrop-blur-2xl',
    border: 'border-violet-200',
    borderAccent: 'border-violet-500',
    accent: 'text-violet-600',
    accentBg: 'bg-violet-600',
    accentLight: 'bg-violet-50',
    gradient: 'from-violet-400 to-purple-700',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-violet-50/50',
    inputBorder: 'border-violet-200',
    buttonHover: 'hover:bg-violet-700',
    progressBar: 'bg-violet-500',
    blob1: 'bg-violet-300/20',
    blob2: 'bg-purple-300/20',
    glow: 'shadow-[0_20px_40px_rgba(139,92,246,0.1)]',
  },

  goldenHour: {
    bg: 'bg-[#FEFCE8]',
    card: 'bg-white/80 backdrop-blur-2xl',
    border: 'border-yellow-200',
    borderAccent: 'border-yellow-500',
    accent: 'text-yellow-600',
    accentBg: 'bg-yellow-600',
    accentLight: 'bg-yellow-50',
    gradient: 'from-yellow-400 to-amber-700',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-yellow-50/50',
    inputBorder: 'border-yellow-200',
    buttonHover: 'hover:bg-yellow-700',
    progressBar: 'bg-yellow-500',
    blob1: 'bg-yellow-300/20',
    blob2: 'bg-amber-300/20',
    glow: 'shadow-[0_20px_40px_rgba(234,179,8,0.1)]',
  },

  arctic: {
    bg: 'bg-[#F0F9FF]',
    card: 'bg-white/80 backdrop-blur-2xl',
    border: 'border-slate-200',
    borderAccent: 'border-sky-400',
    accent: 'text-slate-600',
    accentBg: 'bg-slate-600',
    accentLight: 'bg-slate-50',
    gradient: 'from-slate-400 to-slate-700',
    text: 'text-slate-800',
    muted: 'text-slate-500',
    isLight: true,
    inputBg: 'bg-slate-100',
    inputBorder: 'border-slate-200',
    buttonHover: 'hover:bg-slate-700',
    progressBar: 'bg-slate-500',
    blob1: 'bg-slate-300/20',
    blob2: 'bg-sky-300/20',
    glow: 'shadow-[0_20px_40px_rgba(148,163,184,0.1)]',
  },

  // Dark Themes
  cyberpunk: {
    bg: 'bg-[#05050A]',
    card: 'bg-[#0A0A12]/80 backdrop-blur-3xl',
    border: 'border-cyan-500/20',
    borderAccent: 'border-cyan-400',
    accent: 'text-cyan-400',
    accentBg: 'bg-cyan-500',
    accentLight: 'bg-cyan-950/30',
    gradient: 'from-cyan-400 via-blue-500 to-purple-600',
    text: 'text-slate-100',
    muted: 'text-slate-400',
    isLight: false,
    inputBg: 'bg-slate-900/50',
    inputBorder: 'border-cyan-500/30',
    buttonHover: 'hover:bg-cyan-600',
    progressBar: 'bg-cyan-400',
    blob1: 'bg-cyan-500/10',
    blob2: 'bg-blue-500/10',
    glow: 'shadow-[0_0_40px_rgba(6,182,212,0.2)]',
  },

  'space-odyssey': {
    bg: 'bg-[#020205]',
    card: 'bg-[#0B0B1A]/80 backdrop-blur-3xl',
    border: 'border-violet-500/20',
    borderAccent: 'border-fuchsia-400',
    accent: 'text-violet-400',
    accentBg: 'bg-violet-500',
    accentLight: 'bg-fuchsia-950/30',
    gradient: 'from-violet-600 via-fuchsia-500 to-orange-500',
    text: 'text-slate-100',
    muted: 'text-slate-400',
    isLight: false,
    inputBg: 'bg-slate-900/50',
    inputBorder: 'border-violet-500/30',
    buttonHover: 'hover:bg-violet-600',
    progressBar: 'bg-fuchsia-400',
    blob1: 'bg-fuchsia-500/10',
    blob2: 'bg-purple-500/10',
    glow: 'shadow-[0_0_40px_rgba(217,70,239,0.2)]',
  },

  forestNight: {
    bg: 'bg-[#020C07]',
    card: 'bg-[#05150A]/80 backdrop-blur-2xl',
    border: 'border-emerald-500/20',
    borderAccent: 'border-emerald-400',
    accent: 'text-emerald-400',
    accentBg: 'bg-emerald-500',
    accentLight: 'bg-emerald-950/40',
    gradient: 'from-emerald-400 to-green-800',
    text: 'text-slate-100',
    muted: 'text-slate-400',
    isLight: false,
    inputBg: 'bg-emerald-950/50',
    inputBorder: 'border-emerald-500/30',
    buttonHover: 'hover:bg-emerald-600',
    progressBar: 'bg-emerald-400',
    blob1: 'bg-emerald-500/10',
    blob2: 'bg-green-500/10',
    glow: 'shadow-[0_0_40px_rgba(16,185,129,0.2)]',
  },

  'crimson-dark': {
    bg: 'bg-[#0A0204]',
    card: 'bg-[#120508]/80 backdrop-blur-2xl',
    border: 'border-red-500/20',
    borderAccent: 'border-red-400',
    accent: 'text-red-400',
    accentBg: 'bg-red-500',
    accentLight: 'bg-red-950/40',
    gradient: 'from-red-500 to-rose-900',
    text: 'text-slate-100',
    muted: 'text-slate-400',
    isLight: false,
    inputBg: 'bg-red-950/50',
    inputBorder: 'border-red-500/30',
    buttonHover: 'hover:bg-red-600',
    progressBar: 'bg-red-400',
    blob1: 'bg-red-500/10',
    blob2: 'bg-rose-500/10',
    glow: 'shadow-[0_0_40px_rgba(225,29,72,0.2)]',
  },
};

// Export VIBES array for theme selection UI
export const VIBES = [
  { id: 'minimalist', label: 'Minimalist', gradient: 'from-indigo-600 to-blue-600', desc: 'Clean Academic' },
  { id: 'library-sage', label: 'Library Sage', gradient: 'from-[#8B5E34] to-[#5C3A21]', desc: 'Warm, Scholarly' },
  { id: 'zen-garden', label: 'Zen Garden', gradient: 'from-emerald-500 to-teal-700', desc: 'Natural, Calming' },
  { id: 'oceanBreeze', label: 'Ocean Breeze', gradient: 'from-sky-400 to-blue-700', desc: 'Crisp, Flowing' },
  { id: 'sunrise', label: 'Sunrise', gradient: 'from-amber-400 via-orange-500 to-red-500', desc: 'Bright, Energetic' },
  { id: 'lavenderDream', label: 'Lavender', gradient: 'from-violet-400 to-purple-700', desc: 'Soft, Ethereal' },
  { id: 'goldenHour', label: 'Golden Hour', gradient: 'from-yellow-400 to-amber-700', desc: 'Warm, Cinematic' },
  { id: 'arctic', label: 'Arctic Ice', gradient: 'from-slate-400 to-slate-700', desc: 'Cool, Focused' },
  { id: 'cyberpunk', label: 'Cyberpunk', gradient: 'from-cyan-400 via-blue-500 to-purple-600', desc: 'Neon, Digital' },
  { id: 'space-odyssey', label: 'Cosmic', gradient: 'from-violet-600 via-fuchsia-500 to-orange-500', desc: 'Deep Space' },
  { id: 'forestNight', label: 'Forest Night', gradient: 'from-emerald-400 to-green-800', desc: 'Dark, Organic' },
  { id: 'crimson-dark', label: 'Crimson', gradient: 'from-red-500 to-rose-900', desc: 'Bold, Intense' },
];