import { NextResponse } from 'next/server';
import { prisma } from '@/lib/db/client';
import { createServerSupabaseClient } from '@/lib/supabase/server';

export async function GET() {
  try {
    const supabase = await createServerSupabaseClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    // Get profile with all stats
    const profile = await prisma.profile.findUnique({
      where: { userId: user.id },
      include: {
        achievements: true,
      },
    });

    if (!profile) {
      return NextResponse.json({ error: 'Profile not found' }, { status: 404 });
    }

    // Get user's curriculums to check syllabus status
    const curriculums = await prisma.curriculum.findMany({
      where: { userId: user.id },
      include: {
        subjects: {
          include: {
            chapters: {
              include: {
                progress: {
                  where: { userId: user.id },
                },
              },
            },
          },
        },
      },
    });

    // Calculate real achievement progress
    const totalChaptersCompleted = curriculums.reduce((acc, curr) => {
      return acc + curr.subjects.reduce((subAcc, subject) => {
        return subAcc + subject.chapters.filter(
          ch => ch.progress.some(p => p.completedAt !== null)
        ).length;
      }, 0);
    }, 0);

    const totalChapters = curriculums.reduce((acc, curr) => {
      return acc + curr.subjects.reduce((subAcc, subject) => {
        return subAcc + subject.chapters.length;
      }, 0);
    }, 0);

    // Calculate subject mastery
    const subjectMastery: Record<string, { completed: number; total: number; percentage: number }> = {};
    curriculums.forEach(curr => {
      curr.subjects.forEach(subject => {
        const completed = subject.chapters.filter(
          ch => ch.progress.some(p => p.completedAt !== null)
        ).length;
        subjectMastery[subject.name] = {
          completed,
          total: subject.chapters.length,
          percentage: subject.chapters.length > 0 
            ? Math.round((completed / subject.chapters.length) * 100) 
            : 0,
        };
      });
    });

    // Helper to get count of subjects with 100% mastery
    const subjectsCompleted = Object.values(subjectMastery).filter(s => s.percentage >= 100).length;

    // Helper to get average mastery
    const averageMastery = Object.values(subjectMastery).reduce((sum, s) => sum + s.percentage, 0) / (Object.keys(subjectMastery).length || 1);

    // Build comprehensive achievements list
    const achievements = [
      // 📚 LEARNING ACHIEVEMENTS (Original)
      {
        id: 'learn_first_chapter',
        userId: user.id,
        name: 'First Steps',
        description: 'Complete your first chapter',
        unlocked: totalChaptersCompleted >= 1,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 1),
        total: 1,
        category: 'learning',
      },
      {
        id: 'learn_10_chapters',
        userId: user.id,
        name: 'Knowledge Seeker',
        description: 'Complete 10 chapters',
        unlocked: totalChaptersCompleted >= 10,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 10),
        total: 10,
        category: 'learning',
      },
      {
        id: 'learn_50_chapters',
        userId: user.id,
        name: 'Scholar',
        description: 'Complete 50 chapters',
        unlocked: totalChaptersCompleted >= 50,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 50),
        total: 50,
        category: 'learning',
      },
      {
        id: 'learn_100_chapters',
        userId: user.id,
        name: 'Master Scholar',
        description: 'Complete 100 chapters',
        unlocked: totalChaptersCompleted >= 100,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 100),
        total: 100,
        category: 'learning',
      },

      // 🔥 STREAK ACHIEVEMENTS (Original)
      {
        id: 'streak_3_days',
        userId: user.id,
        name: 'Getting Warm',
        description: 'Maintain a 3-day learning streak',
        unlocked: (profile.currentStreak || 0) >= 3,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 3),
        total: 3,
        category: 'streak',
      },
      {
        id: 'streak_7_days',
        userId: user.id,
        name: 'Week Warrior',
        description: 'Maintain a 7-day streak',
        unlocked: (profile.currentStreak || 0) >= 7,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 7),
        total: 7,
        category: 'streak',
      },
      {
        id: 'streak_30_days',
        userId: user.id,
        name: 'Monthly Master',
        description: 'Maintain a 30-day streak',
        unlocked: (profile.currentStreak || 0) >= 30,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 30),
        total: 30,
        category: 'streak',
      },
      {
        id: 'streak_100_days',
        userId: user.id,
        name: 'Century Club',
        description: 'Maintain a 100-day streak',
        unlocked: (profile.currentStreak || 0) >= 100,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 100),
        total: 100,
        category: 'streak',
      },

      // 🎯 MASTERY ACHIEVEMENTS (Original)
      {
        id: 'mastery_subject_100',
        userId: user.id,
        name: 'Subject Master',
        description: 'Achieve 100% mastery in any subject',
        unlocked: subjectsCompleted >= 1,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 1),
        total: 1,
        category: 'mastery',
      },
      {
        id: 'mastery_all_subjects',
        userId: user.id,
        name: 'Polymath',
        description: 'Achieve 100% mastery in all subjects',
        unlocked: Object.values(subjectMastery).length > 0 && 
                  Object.values(subjectMastery).every(s => s.percentage >= 100),
        unlockedAt: null,
        progress: subjectsCompleted,
        total: Object.values(subjectMastery).length || 1,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_90',
        userId: user.id,
        name: 'Excellence',
        description: 'Maintain 90%+ average mastery',
        unlocked: averageMastery >= 90,
        unlockedAt: null,
        progress: Math.min(averageMastery, 90),
        total: 90,
        category: 'mastery',
      },

      // 📝 TEST ACHIEVEMENTS (Original)
      {
        id: 'test_first',
        userId: user.id,
        name: 'Test Taker',
        description: 'Complete your first assessment',
        unlocked: (profile.testsCompleted || 0) >= 1,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 1),
        total: 1,
        category: 'learning',
      },
      {
        id: 'test_10',
        userId: user.id,
        name: 'Exam Veteran',
        description: 'Complete 10 assessments',
        unlocked: (profile.testsCompleted || 0) >= 10,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 10),
        total: 10,
        category: 'learning',
      },
      {
        id: 'test_perfect',
        userId: user.id,
        name: 'Perfect Score',
        description: 'Get 100% on any assessment',
        unlocked: averageMastery >= 100,
        unlockedAt: null,
        progress: averageMastery >= 100 ? 1 : 0,
        total: 1,
        category: 'mastery',
      },

      // ⏱️ TIME ACHIEVEMENTS (Original)
      {
        id: 'time_1_hour',
        userId: user.id,
        name: 'Time Invested',
        description: 'Study for 1 hour total',
        unlocked: (profile.totalStudyMinutes || 0) >= 60,
        unlockedAt: null,
        progress: Math.min(Math.floor((profile.totalStudyMinutes || 0) / 60), 1),
        total: 1,
        category: 'learning',
      },
      {
        id: 'time_10_hours',
        userId: user.id,
        name: 'Dedicated Learner',
        description: 'Study for 10 hours total',
        unlocked: (profile.totalStudyMinutes || 0) >= 600,
        unlockedAt: null,
        progress: Math.min(Math.floor((profile.totalStudyMinutes || 0) / 60), 10),
        total: 10,
        category: 'learning',
      },
      {
        id: 'time_100_hours',
        userId: user.id,
        name: 'Century Scholar',
        description: 'Study for 100 hours total',
        unlocked: (profile.totalStudyMinutes || 0) >= 6000,
        unlockedAt: null,
        progress: Math.min(Math.floor((profile.totalStudyMinutes || 0) / 60), 100),
        total: 100,
        category: 'learning',
      },

      // 📖 SYLLABUS ACHIEVEMENTS (Original)
      {
        id: 'syllabus_uploaded',
        userId: user.id,
        name: 'Curriculum Builder',
        description: 'Upload your first syllabus',
        unlocked: curriculums.length >= 1,
        unlockedAt: null,
        progress: Math.min(curriculums.length, 1),
        total: 1,
        category: 'learning',
      },
      {
        id: 'syllabus_3_subjects',
        userId: user.id,
        name: 'Subject Explorer',
        description: 'Have 3+ subjects in your curriculum',
        unlocked: curriculums.reduce((acc, c) => acc + c.subjects.length, 0) >= 3,
        unlockedAt: null,
        progress: Math.min(curriculums.reduce((acc, c) => acc + c.subjects.length, 0), 3),
        total: 3,
        category: 'learning',
      },

      // 🏆 POINTS ACHIEVEMENTS (Original)
      {
        id: 'points_1000',
        userId: user.id,
        name: 'Rising Star',
        description: 'Earn 1,000 XP',
        unlocked: (profile.totalPoints || 0) >= 1000,
        unlockedAt: null,
        progress: Math.min(Math.floor((profile.totalPoints || 0) / 1000), 1),
        total: 1,
        category: 'learning',
      },
      {
        id: 'points_10000',
        userId: user.id,
        name: 'Star Performer',
        description: 'Earn 10,000 XP',
        unlocked: (profile.totalPoints || 0) >= 10000,
        unlockedAt: null,
        progress: Math.min(Math.floor((profile.totalPoints || 0) / 10000), 1),
        total: 1,
        category: 'learning',
      },
      {
        id: 'points_50000',
        userId: user.id,
        name: 'Legend',
        description: 'Earn 50,000 XP',
        unlocked: (profile.totalPoints || 0) >= 50000,
        unlockedAt: null,
        progress: Math.min(Math.floor((profile.totalPoints || 0) / 50000), 1),
        total: 1,
        category: 'learning',
      },

      // ==========================================================================
      // NEW ACHIEVEMENTS (3x expansion)
      // ==========================================================================

      // 📚 LEARNING – more granular chapter milestones
      {
        id: 'learn_5_chapters',
        userId: user.id,
        name: 'Quick Learner',
        description: 'Complete 5 chapters',
        unlocked: totalChaptersCompleted >= 5,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 5),
        total: 5,
        category: 'learning',
      },
      {
        id: 'learn_20_chapters',
        userId: user.id,
        name: 'Bookworm',
        description: 'Complete 20 chapters',
        unlocked: totalChaptersCompleted >= 20,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 20),
        total: 20,
        category: 'learning',
      },
      {
        id: 'learn_30_chapters',
        userId: user.id,
        name: 'Diligent Student',
        description: 'Complete 30 chapters',
        unlocked: totalChaptersCompleted >= 30,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 30),
        total: 30,
        category: 'learning',
      },
      {
        id: 'learn_40_chapters',
        userId: user.id,
        name: 'Consistent Learner',
        description: 'Complete 40 chapters',
        unlocked: totalChaptersCompleted >= 40,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 40),
        total: 40,
        category: 'learning',
      },
      {
        id: 'learn_75_chapters',
        userId: user.id,
        name: 'Advanced Scholar',
        description: 'Complete 75 chapters',
        unlocked: totalChaptersCompleted >= 75,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 75),
        total: 75,
        category: 'learning',
      },
      {
        id: 'learn_150_chapters',
        userId: user.id,
        name: 'Grand Scholar',
        description: 'Complete 150 chapters',
        unlocked: totalChaptersCompleted >= 150,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 150),
        total: 150,
        category: 'learning',
      },
      {
        id: 'learn_200_chapters',
        userId: user.id,
        name: 'Master of Knowledge',
        description: 'Complete 200 chapters',
        unlocked: totalChaptersCompleted >= 200,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 200),
        total: 200,
        category: 'learning',
      },
      {
        id: 'learn_250_chapters',
        userId: user.id,
        name: 'Enlightened',
        description: 'Complete 250 chapters',
        unlocked: totalChaptersCompleted >= 250,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 250),
        total: 250,
        category: 'learning',
      },
      {
        id: 'learn_300_chapters',
        userId: user.id,
        name: 'Sage',
        description: 'Complete 300 chapters',
        unlocked: totalChaptersCompleted >= 300,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 300),
        total: 300,
        category: 'learning',
      },
      {
        id: 'learn_500_chapters',
        userId: user.id,
        name: 'Legendary Scholar',
        description: 'Complete 500 chapters',
        unlocked: totalChaptersCompleted >= 500,
        unlockedAt: null,
        progress: Math.min(totalChaptersCompleted, 500),
        total: 500,
        category: 'learning',
      },

      // 🔥 STREAK – more granular
      {
        id: 'streak_2_days',
        userId: user.id,
        name: 'Just Started',
        description: '2‑day streak',
        unlocked: (profile.currentStreak || 0) >= 2,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 2),
        total: 2,
        category: 'streak',
      },
      {
        id: 'streak_5_days',
        userId: user.id,
        name: 'Five‑Day Habit',
        description: '5‑day streak',
        unlocked: (profile.currentStreak || 0) >= 5,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 5),
        total: 5,
        category: 'streak',
      },
      {
        id: 'streak_10_days',
        userId: user.id,
        name: 'Double Digits',
        description: '10‑day streak',
        unlocked: (profile.currentStreak || 0) >= 10,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 10),
        total: 10,
        category: 'streak',
      },
      {
        id: 'streak_15_days',
        userId: user.id,
        name: 'Half‑Month Warrior',
        description: '15‑day streak',
        unlocked: (profile.currentStreak || 0) >= 15,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 15),
        total: 15,
        category: 'streak',
      },
      {
        id: 'streak_20_days',
        userId: user.id,
        name: 'Three‑Week Club',
        description: '20‑day streak',
        unlocked: (profile.currentStreak || 0) >= 20,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 20),
        total: 20,
        category: 'streak',
      },
      {
        id: 'streak_25_days',
        userId: user.id,
        name: 'Almost a Month',
        description: '25‑day streak',
        unlocked: (profile.currentStreak || 0) >= 25,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 25),
        total: 25,
        category: 'streak',
      },
      {
        id: 'streak_45_days',
        userId: user.id,
        name: 'Month and a Half',
        description: '45‑day streak',
        unlocked: (profile.currentStreak || 0) >= 45,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 45),
        total: 45,
        category: 'streak',
      },
      {
        id: 'streak_60_days',
        userId: user.id,
        name: 'Two‑Month Veteran',
        description: '60‑day streak',
        unlocked: (profile.currentStreak || 0) >= 60,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 60),
        total: 60,
        category: 'streak',
      },
      {
        id: 'streak_90_days',
        userId: user.id,
        name: 'Quarter of a Year',
        description: '90‑day streak',
        unlocked: (profile.currentStreak || 0) >= 90,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 90),
        total: 90,
        category: 'streak',
      },
      {
        id: 'streak_120_days',
        userId: user.id,
        name: 'Four‑Month Master',
        description: '120‑day streak',
        unlocked: (profile.currentStreak || 0) >= 120,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 120),
        total: 120,
        category: 'streak',
      },
      {
        id: 'streak_150_days',
        userId: user.id,
        name: 'Half‑Year Journey',
        description: '150‑day streak',
        unlocked: (profile.currentStreak || 0) >= 150,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 150),
        total: 150,
        category: 'streak',
      },
      {
        id: 'streak_180_days',
        userId: user.id,
        name: 'Six‑Month Streak',
        description: '180‑day streak',
        unlocked: (profile.currentStreak || 0) >= 180,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 180),
        total: 180,
        category: 'streak',
      },
      {
        id: 'streak_365_days',
        userId: user.id,
        name: 'Year of Growth',
        description: '365‑day streak',
        unlocked: (profile.currentStreak || 0) >= 365,
        unlockedAt: null,
        progress: Math.min(profile.currentStreak || 0, 365),
        total: 365,
        category: 'streak',
      },

      // 🎯 MASTERY – more subjects completed
      {
        id: 'mastery_2_subjects',
        userId: user.id,
        name: 'Double Expert',
        description: 'Complete 2 subjects',
        unlocked: subjectsCompleted >= 2,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 2),
        total: 2,
        category: 'mastery',
      },
      {
        id: 'mastery_3_subjects',
        userId: user.id,
        name: 'Triple Threat',
        description: 'Complete 3 subjects',
        unlocked: subjectsCompleted >= 3,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 3),
        total: 3,
        category: 'mastery',
      },
      {
        id: 'mastery_4_subjects',
        userId: user.id,
        name: 'Quadruple Expert',
        description: 'Complete 4 subjects',
        unlocked: subjectsCompleted >= 4,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 4),
        total: 4,
        category: 'mastery',
      },
      {
        id: 'mastery_5_subjects',
        userId: user.id,
        name: 'Penta‑Master',
        description: 'Complete 5 subjects',
        unlocked: subjectsCompleted >= 5,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 5),
        total: 5,
        category: 'mastery',
      },
      {
        id: 'mastery_6_subjects',
        userId: user.id,
        name: 'Six‑Pack Scholar',
        description: 'Complete 6 subjects',
        unlocked: subjectsCompleted >= 6,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 6),
        total: 6,
        category: 'mastery',
      },
      {
        id: 'mastery_7_subjects',
        userId: user.id,
        name: 'Seven Wonders',
        description: 'Complete 7 subjects',
        unlocked: subjectsCompleted >= 7,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 7),
        total: 7,
        category: 'mastery',
      },
      {
        id: 'mastery_8_subjects',
        userId: user.id,
        name: 'Octa‑Master',
        description: 'Complete 8 subjects',
        unlocked: subjectsCompleted >= 8,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 8),
        total: 8,
        category: 'mastery',
      },
      {
        id: 'mastery_9_subjects',
        userId: user.id,
        name: 'Nine Lives of Knowledge',
        description: 'Complete 9 subjects',
        unlocked: subjectsCompleted >= 9,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 9),
        total: 9,
        category: 'mastery',
      },
      {
        id: 'mastery_10_subjects',
        userId: user.id,
        name: 'Deca‑Master',
        description: 'Complete 10 subjects',
        unlocked: subjectsCompleted >= 10,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 10),
        total: 10,
        category: 'mastery',
      },

      // Average mastery milestones
      {
        id: 'mastery_avg_50',
        userId: user.id,
        name: 'Halfway There',
        description: 'Achieve 50% average mastery',
        unlocked: averageMastery >= 50,
        unlockedAt: null,
        progress: Math.min(averageMastery, 50),
        total: 50,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_60',
        userId: user.id,
        name: 'Passing Grade',
        description: 'Achieve 60% average mastery',
        unlocked: averageMastery >= 60,
        unlockedAt: null,
        progress: Math.min(averageMastery, 60),
        total: 60,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_70',
        userId: user.id,
        name: 'Solid Foundation',
        description: 'Achieve 70% average mastery',
        unlocked: averageMastery >= 70,
        unlockedAt: null,
        progress: Math.min(averageMastery, 70),
        total: 70,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_80',
        userId: user.id,
        name: 'Almost There',
        description: 'Achieve 80% average mastery',
        unlocked: averageMastery >= 80,
        unlockedAt: null,
        progress: Math.min(averageMastery, 80),
        total: 80,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_85',
        userId: user.id,
        name: 'High Achiever',
        description: 'Achieve 85% average mastery',
        unlocked: averageMastery >= 85,
        unlockedAt: null,
        progress: Math.min(averageMastery, 85),
        total: 85,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_92',
        userId: user.id,
        name: 'Excellence Plus',
        description: 'Achieve 92% average mastery',
        unlocked: averageMastery >= 92,
        unlockedAt: null,
        progress: Math.min(averageMastery, 92),
        total: 92,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_95',
        userId: user.id,
        name: 'Near Perfection',
        description: 'Achieve 95% average mastery',
        unlocked: averageMastery >= 95,
        unlockedAt: null,
        progress: Math.min(averageMastery, 95),
        total: 95,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_97',
        userId: user.id,
        name: 'Elite Scholar',
        description: 'Achieve 97% average mastery',
        unlocked: averageMastery >= 97,
        unlockedAt: null,
        progress: Math.min(averageMastery, 97),
        total: 97,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_98',
        userId: user.id,
        name: 'Almost Flawless',
        description: 'Achieve 98% average mastery',
        unlocked: averageMastery >= 98,
        unlockedAt: null,
        progress: Math.min(averageMastery, 98),
        total: 98,
        category: 'mastery',
      },
      {
        id: 'mastery_avg_99',
        userId: user.id,
        name: 'Virtuoso',
        description: 'Achieve 99% average mastery',
        unlocked: averageMastery >= 99,
        unlockedAt: null,
        progress: Math.min(averageMastery, 99),
        total: 99,
        category: 'mastery',
      },

      // 📝 TESTS – more granular
      {
        id: 'test_5',
        userId: user.id,
        name: 'Quiz Regular',
        description: 'Complete 5 assessments',
        unlocked: (profile.testsCompleted || 0) >= 5,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 5),
        total: 5,
        category: 'learning',
      },
      {
        id: 'test_20',
        userId: user.id,
        name: 'Assessment Pro',
        description: 'Complete 20 assessments',
        unlocked: (profile.testsCompleted || 0) >= 20,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 20),
        total: 20,
        category: 'learning',
      },
      {
        id: 'test_30',
        userId: user.id,
        name: 'Test Champion',
        description: 'Complete 30 assessments',
        unlocked: (profile.testsCompleted || 0) >= 30,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 30),
        total: 30,
        category: 'learning',
      },
      {
        id: 'test_40',
        userId: user.id,
        name: 'Exam Master',
        description: 'Complete 40 assessments',
        unlocked: (profile.testsCompleted || 0) >= 40,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 40),
        total: 40,
        category: 'learning',
      },
      {
        id: 'test_50',
        userId: user.id,
        name: 'Half‑Century of Tests',
        description: 'Complete 50 assessments',
        unlocked: (profile.testsCompleted || 0) >= 50,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 50),
        total: 50,
        category: 'learning',
      },
      {
        id: 'test_60',
        userId: user.id,
        name: 'Test Veteran',
        description: 'Complete 60 assessments',
        unlocked: (profile.testsCompleted || 0) >= 60,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 60),
        total: 60,
        category: 'learning',
      },
      {
        id: 'test_70',
        userId: user.id,
        name: 'Assessment Expert',
        description: 'Complete 70 assessments',
        unlocked: (profile.testsCompleted || 0) >= 70,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 70),
        total: 70,
        category: 'learning',
      },
      {
        id: 'test_80',
        userId: user.id,
        name: 'Octogenarian of Tests',
        description: 'Complete 80 assessments',
        unlocked: (profile.testsCompleted || 0) >= 80,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 80),
        total: 80,
        category: 'learning',
      },
      {
        id: 'test_90',
        userId: user.id,
        name: 'Nonagenarian Scholar',
        description: 'Complete 90 assessments',
        unlocked: (profile.testsCompleted || 0) >= 90,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 90),
        total: 90,
        category: 'learning',
      },
      {
        id: 'test_100',
        userId: user.id,
        name: 'Century of Tests',
        description: 'Complete 100 assessments',
        unlocked: (profile.testsCompleted || 0) >= 100,
        unlockedAt: null,
        progress: Math.min(profile.testsCompleted || 0, 100),
        total: 100,
        category: 'learning',
      },

      // Perfect scores
      {
        id: 'test_perfect_3',
        userId: user.id,
        name: 'Perfect Hat‑Trick',
        description: 'Get 3 perfect scores',
        unlocked: (profile.perfectTests || 0) >= 3,
        unlockedAt: null,
        progress: Math.min(profile.perfectTests || 0, 3),
        total: 3,
        category: 'mastery',
      },
      {
        id: 'test_perfect_5',
        userId: user.id,
        name: 'Perfect Quintet',
        description: 'Get 5 perfect scores',
        unlocked: (profile.perfectTests || 0) >= 5,
        unlockedAt: null,
        progress: Math.min(profile.perfectTests || 0, 5),
        total: 5,
        category: 'mastery',
      },
      {
        id: 'test_perfect_10',
        userId: user.id,
        name: 'Perfect Deca',
        description: 'Get 10 perfect scores',
        unlocked: (profile.perfectTests || 0) >= 10,
        unlockedAt: null,
        progress: Math.min(profile.perfectTests || 0, 10),
        total: 10,
        category: 'mastery',
      },
      {
        id: 'test_perfect_20',
        userId: user.id,
        name: 'Double‑Digit Perfection',
        description: 'Get 20 perfect scores',
        unlocked: (profile.perfectTests || 0) >= 20,
        unlockedAt: null,
        progress: Math.min(profile.perfectTests || 0, 20),
        total: 20,
        category: 'mastery',
      },

      // ⏱️ TIME – more granular (in hours)
      ...[30, 120, 300, 1200, 1800, 2400, 3000, 3600, 7200, 14400].map((minutes, index) => {
        const hours = minutes / 60;
        const names = [
          'Half‑Hour Focus',
          'Two‑Hour Session',
          'Five‑Hour Marathon',
          'Twenty Hours',
          'Thirty Hours',
          'Forty Hours',
          'Fifty Hours',
          'Sixty Hours',
          'One‑Hundred‑Twenty Hours',
          'Two‑Hundred‑Forty Hours',
        ];
        const desc = [
          'Study for 30 minutes total',
          'Study for 2 hours total',
          'Study for 5 hours total',
          'Study for 20 hours total',
          'Study for 30 hours total',
          'Study for 40 hours total',
          'Study for 50 hours total',
          'Study for 60 hours total',
          'Study for 120 hours total',
          'Study for 240 hours total',
        ];
        return {
          id: `time_${minutes}_minutes`,
          userId: user.id,
          name: names[index],
          description: desc[index],
          unlocked: (profile.totalStudyMinutes || 0) >= minutes,
          unlockedAt: null,
          progress: Math.min(profile.totalStudyMinutes || 0, minutes),
          total: minutes,
          category: 'learning',
        };
      }),

      // 🏆 POINTS – more granular
      {
        id: 'points_500',
        userId: user.id,
        name: '500 Points',
        description: 'Earn 500 XP',
        unlocked: (profile.totalPoints || 0) >= 500,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 500),
        total: 500,
        category: 'learning',
      },
      {
        id: 'points_2500',
        userId: user.id,
        name: '2,500 Points',
        description: 'Earn 2,500 XP',
        unlocked: (profile.totalPoints || 0) >= 2500,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 2500),
        total: 2500,
        category: 'learning',
      },
      {
        id: 'points_5000',
        userId: user.id,
        name: '5,000 Points',
        description: 'Earn 5,000 XP',
        unlocked: (profile.totalPoints || 0) >= 5000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 5000),
        total: 5000,
        category: 'learning',
      },
      {
        id: 'points_7500',
        userId: user.id,
        name: '7,500 Points',
        description: 'Earn 7,500 XP',
        unlocked: (profile.totalPoints || 0) >= 7500,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 7500),
        total: 7500,
        category: 'learning',
      },
      {
        id: 'points_15000',
        userId: user.id,
        name: '15,000 Points',
        description: 'Earn 15,000 XP',
        unlocked: (profile.totalPoints || 0) >= 15000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 15000),
        total: 15000,
        category: 'learning',
      },
      {
        id: 'points_20000',
        userId: user.id,
        name: '20,000 Points',
        description: 'Earn 20,000 XP',
        unlocked: (profile.totalPoints || 0) >= 20000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 20000),
        total: 20000,
        category: 'learning',
      },
      {
        id: 'points_30000',
        userId: user.id,
        name: '30,000 Points',
        description: 'Earn 30,000 XP',
        unlocked: (profile.totalPoints || 0) >= 30000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 30000),
        total: 30000,
        category: 'learning',
      },
      {
        id: 'points_40000',
        userId: user.id,
        name: '40,000 Points',
        description: 'Earn 40,000 XP',
        unlocked: (profile.totalPoints || 0) >= 40000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 40000),
        total: 40000,
        category: 'learning',
      },
      {
        id: 'points_75000',
        userId: user.id,
        name: '75,000 Points',
        description: 'Earn 75,000 XP',
        unlocked: (profile.totalPoints || 0) >= 75000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 75000),
        total: 75000,
        category: 'learning',
      },
      {
        id: 'points_100000',
        userId: user.id,
        name: '100,000 Points',
        description: 'Earn 100,000 XP',
        unlocked: (profile.totalPoints || 0) >= 100000,
        unlockedAt: null,
        progress: Math.min(profile.totalPoints || 0, 100000),
        total: 100000,
        category: 'learning',
      },

      // 📖 SYLLABUS – more thresholds
      {
        id: 'syllabus_2',
        userId: user.id,
        name: 'Dual Curriculum',
        description: 'Upload 2 syllabi',
        unlocked: curriculums.length >= 2,
        unlockedAt: null,
        progress: Math.min(curriculums.length, 2),
        total: 2,
        category: 'learning',
      },
      {
        id: 'syllabus_3',
        userId: user.id,
        name: 'Triple Syllabus',
        description: 'Upload 3 syllabi',
        unlocked: curriculums.length >= 3,
        unlockedAt: null,
        progress: Math.min(curriculums.length, 3),
        total: 3,
        category: 'learning',
      },
      {
        id: 'syllabus_4',
        userId: user.id,
        name: 'Quadruple Syllabus',
        description: 'Upload 4 syllabi',
        unlocked: curriculums.length >= 4,
        unlockedAt: null,
        progress: Math.min(curriculums.length, 4),
        total: 4,
        category: 'learning',
      },
      {
        id: 'syllabus_5',
        userId: user.id,
        name: 'Penta Syllabus',
        description: 'Upload 5 syllabi',
        unlocked: curriculums.length >= 5,
        unlockedAt: null,
        progress: Math.min(curriculums.length, 5),
        total: 5,
        category: 'learning',
      },
      {
        id: 'syllabus_10',
        userId: user.id,
        name: 'Deca Syllabus',
        description: 'Upload 10 syllabi',
        unlocked: curriculums.length >= 10,
        unlockedAt: null,
        progress: Math.min(curriculums.length, 10),
        total: 10,
        category: 'learning',
      },

      // Subjects in curriculum (total across all syllabi)
      {
        id: 'subjects_5',
        userId: user.id,
        name: 'Five Subjects',
        description: 'Study 5 different subjects',
        unlocked: curriculums.reduce((acc, c) => acc + c.subjects.length, 0) >= 5,
        unlockedAt: null,
        progress: Math.min(curriculums.reduce((acc, c) => acc + c.subjects.length, 0), 5),
        total: 5,
        category: 'learning',
      },
      {
        id: 'subjects_10',
        userId: user.id,
        name: 'Deca Subject',
        description: 'Study 10 different subjects',
        unlocked: curriculums.reduce((acc, c) => acc + c.subjects.length, 0) >= 10,
        unlockedAt: null,
        progress: Math.min(curriculums.reduce((acc, c) => acc + c.subjects.length, 0), 10),
        total: 10,
        category: 'learning',
      },
      {
        id: 'subjects_15',
        userId: user.id,
        name: 'Quindecim Subjects',
        description: 'Study 15 different subjects',
        unlocked: curriculums.reduce((acc, c) => acc + c.subjects.length, 0) >= 15,
        unlockedAt: null,
        progress: Math.min(curriculums.reduce((acc, c) => acc + c.subjects.length, 0), 15),
        total: 15,
        category: 'learning',
      },
      {
        id: 'subjects_20',
        userId: user.id,
        name: 'Viginti Subjects',
        description: 'Study 20 different subjects',
        unlocked: curriculums.reduce((acc, c) => acc + c.subjects.length, 0) >= 20,
        unlockedAt: null,
        progress: Math.min(curriculums.reduce((acc, c) => acc + c.subjects.length, 0), 20),
        total: 20,
        category: 'learning',
      },

      // SPECIAL – fun, one‑off achievements
      {
        id: 'special_first_login',
        userId: user.id,
        name: 'Welcome Aboard',
        description: 'Log in for the first time',
        unlocked: true, // always true if user exists
        unlockedAt: null,
        progress: 1,
        total: 1,
        category: 'special',
      },
      {
        id: 'special_profile_complete',
        userId: user.id,
        name: 'Identity Established',
        description: 'Fill in your profile details',
        unlocked: !!(profile.fullName && profile.age && profile.gender && profile.school && profile.board),
        unlockedAt: null,
        progress: [profile.fullName, profile.age, profile.gender, profile.school, profile.board].filter(Boolean).length,
        total: 5,
        category: 'special',
      },
      {
        id: 'special_avatar_set',
        userId: user.id,
        name: 'Picture Perfect',
        description: 'Upload a profile picture',
        unlocked: !!profile.avatarUrl,
        unlockedAt: null,
        progress: profile.avatarUrl ? 1 : 0,
        total: 1,
        category: 'special',
      },
      {
        id: 'special_night_owl',
        userId: user.id,
        name: 'Night Owl',
        description: 'Study after midnight',
        unlocked: false, // requires tracking; we can't compute here, so leave as false
        unlockedAt: null,
        progress: 0,
        total: 1,
        category: 'special',
      },
      {
        id: 'special_early_bird',
        userId: user.id,
        name: 'Early Bird',
        description: 'Study before 8 AM',
        unlocked: false,
        unlockedAt: null,
        progress: 0,
        total: 1,
        category: 'special',
      },
      {
        id: 'special_weekend_warrior',
        userId: user.id,
        name: 'Weekend Warrior',
        description: 'Study on a Saturday or Sunday',
        unlocked: false,
        unlockedAt: null,
        progress: 0,
        total: 1,
        category: 'special',
      },
      {
        id: 'special_philosopher_stone',
        userId: user.id,
        name: 'Philosopher\'s Stone',
        description: 'Complete a subject with 100% mastery',
        unlocked: subjectsCompleted >= 1,
        unlockedAt: null,
        progress: Math.min(subjectsCompleted, 1),
        total: 1,
        category: 'special',
      },
      {
        id: 'special_completionist',
        userId: user.id,
        name: 'Completionist',
        description: 'Complete all available subjects',
        unlocked: subjectsCompleted === Object.values(subjectMastery).length && Object.values(subjectMastery).length > 0,
        unlockedAt: null,
        progress: subjectsCompleted,
        total: Object.values(subjectMastery).length || 1,
        category: 'special',
      },
    ];

    return NextResponse.json({
      success: true,
      achievements,
      stats: {
        totalChaptersCompleted,
        totalChapters,
        subjectMastery,
        curriculumsCount: curriculums.length,
      },
    });

  } catch (error: any) {
    console.error('Achievements Fetch Error:', error);
    return NextResponse.json(
      { error: 'Failed to fetch achievements.', details: error.message }, 
      { status: 500 }
    );
  }
}